language: ruby
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
before_script:
  - "mysql -e 'create database native_enum_test;' >/dev/null"
  - "cp spec/{.travis.,}database.yml"
script: bundle exec rake spec:rails_all
sudo: false
