language: ruby
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
matrix:
  allow_failures:
    # Allow 2.5 to fail until Travis CI bug is fixed. See:
    # * https://github.com/travis-ci/travis-ci/issues/8978
    # * https://github.com/travis-ci/travis-ci/issues/8969
    - rvm: "2.5"
before_script:
  - "cp spec/{.travis.,}database.yml"
  - "bundle exec rake db:prepare"
script: bundle exec rake spec:rails_all
sudo: false
